parameters:
    eface_contact.admin_email: centras11@gmail.com
    eface_contact.service.contact.class: Eface\ContactBundle\Service\ContactManager

services:
    eface.service.contact_manager:
        class: %eface_contact.service.contact.class%
        arguments: ["@doctrine", "@mailer"]

